periods = {"1st":(1,4),"2nd":(15,19)}
DATA_DIR = "."
DB_FILE = "SASM.ftr"
NEW_HIRE = 45 # Number of days considered a new Hire
VAR_TO_TARGET = 0.5 # Allowed variance to target
SUSP_ABS = 0.75
FT2_GOAL = 88
DL_ABS_VAR_ITM_target = -50
Billability_Target = 50
ALLOWED_VAR = -0.48